version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: shareit-postgres
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # для кастомных скриптов
    restart: unless-stopped

volumes:
  postgres_data: